version: '3.8'
networks:
  devaten-dashboard-mysql:
    name: devaten-dashboard-mysql
    
services:

  devaten-activemq:
    image: rmohr/activemq:5.15.9
    container_name: devaten-activemq
    restart: unless-stopped
    ports:
      - "8161:8161"
      - "61616:61616"
    networks:
      - devaten-dashboard-mysql

  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: devaten
    ports:
      - 0.0.0.0:3306:3306
    volumes:
      # Files
      - ./mysql/my.cnf:/etc/alternatives/my.cnf
      # Dirs
      - ./mysql/datadir/:/var/lib/mysql:rw
      - "./mysql/dump.sql:/docker-entrypoint-initdb.d/mysql/dump.sql"
    command:
      - --sql_mode=
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 30s
      timeout: 2s
      retries: 15
    networks:
      - devaten-dashboard-mysql
    
  onpremise-postgresqlagent-container:
    image: devaten/on-premises-postgresql-agent
    container_name: onpremise-postgresqlagent-container
    restart: unless-stopped
    ports:
      - "8112:8112"
    volumes:
      - ./mysql/h2:/opt/h2-data:rw
    networks:
      - devaten-dashboard-mysql

  devaten-dashboard-container:
    image: devaten/devaten-dashboard:3.4.2
    container_name: devaten-dashboard-container
    restart: always 
    depends_on: 
      mysqldb: 
        condition: service_healthy
    ports:
      - 8081:8081
    networks:
      - devaten-dashboard-mysql


volumes:
  h2-data: {}
